# Generated by Django 4.2.13 on 2024-07-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-created_date",)},
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="updated_at",
            new_name="updated_date",
        ),
    ]
