# Generated by Django 4.2.13 on 2024-07-18 10:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_login_require"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(max_length=1024),
        ),
    ]
